# .github/workflows/lint.yaml
name: Python Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and configure uv
        run: |
          pip install uv
          uv venv

      - name: Cache UV dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Dependencies
        run: |
          uv pip install -e ".[dev]"

      - name: Run Ruff Lint and Format Checks
        run: |
          # Run the linter
          uv run ruff check .
          # Run the formatter in check-only mode
          uv run ruff format --check .

      - name: Run Mypy Type Checker
        run: |
          uv run mypy .

      - name: Run Bandit Security Scan
        run: |
          # Use -r to scan recursively and -c to use our config file
          uv run bandit -r . -c pyproject.toml
